addons:
  firefox: latest
language: node_js
node_js:
  - "6.9.1"
install:
  - npm install
  - npm install -g typings
before_script:
  - typings install
script:
  - npm test
  - npm run build:prod
notifications:
  email: false
  hipchat: 861e4f14f03ed33d069f1083a6c9f5@2679708
