language: node_js
node_js:
  - "6.9.1"
install:
  - npm run install:dev
script:
  - npm test
  - npm start -- build
  - npm start -- mobile.setup
notifications:
  email: false
  hipchat: 861e4f14f03ed33d069f1083a6c9f5@2679708
